/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "gpio.h"
#include "usart.h"

uint8_t tx[] = "Hello World";

void Delay(void){for(uint32_t i = 0; i < 250000; i++);}

void Button_Init(void){
    GPIO_Handle_t button;

    button.pGPIOx = GPIOE;
    GPIO_ClockControl(GPIOE, ENABLE);

    button.GPIOx_CFG.pin_number = GPIO_PIN_3;
    button.GPIOx_CFG.pin_mode = GPIO_MODE_IN;
    button.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;
    button.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_PIN_PU;

    GPIO_Init(&button);
}

void USART_GPIO_Init(void){
	GPIO_Handle_t usart_gpio;

	usart_gpio.pGPIOx = GPIOA;
	GPIO_ClockControl(GPIOA, ENABLE);

	//PA0 - UART4 TX
	usart_gpio.GPIOx_CFG.pin_number = GPIO_PIN_9;
	usart_gpio.GPIOx_CFG.pin_mode = GPIO_MODE_ALT_FN;
	usart_gpio.GPIOx_CFG.pin_alt_func_mode = 7;
	usart_gpio.GPIOx_CFG.pin_op_type = GPIO_OUT_PP;
	usart_gpio.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_NO_PUPD;
	usart_gpio.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;

	GPIO_Init(&usart_gpio);
}

USART_Handle_t usart1;

void USART1_Init(void){
	usart1.pUSARTx = USART1;

	USART_ClockControl(USART1, ENABLE);

	usart1.USART_Config.USART_Mode = USART_MODE_ONLY_TX;
	usart1.USART_Config.USART_Baud = USART_STD_BAUD_115200;
	usart1.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	usart1.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
	usart1.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	usart1.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;

	USART_Init(&usart1);
}

int main(void){
	Button_Init();
	USART_GPIO_Init();
	USART1_Init();

	USART_PeripheralControl(USART1, ENABLE);

	while(1){
		while(GPIO_ReadPin(GPIOE, GPIO_PIN_3) == 1);
		Delay();

		while(GPIO_ReadPin(GPIOE, GPIO_PIN_3) == 0);
		Delay();

		USART_Transmit(&usart1, tx, strlen((char*)tx));
	}
}
